### CATEGORY CREATE
POST http://localhost:3000/api/v1/chapter
Content-Type: application/json

{
    "chapterName":"Chapter-3 Pendahuluan",
    "classCode":"U0",
    "isFree":false
}

####
GET http://localhost:3000/api/v1/chapter


####
GET http://localhost:3000/api/v1/chapter/2

###
PUT http://localhost:3000/api/v1/chapter/1
Content-Type: application/json

{
    "chapterName":"Chapter-1 Pendahuluan",
    "classCode":"UD0",
    "isFree":true
}

####
DELETE http://localhost:3000/api/v1/chapter/35