### CATEGORY CREATE
POST http://localhost:3000/api/v1/category
Content-Type: application/json

{
    "categoryName":"Product Management",
    "thumbnailPictureCategory"
}

#### GET ALL CATEGORY AND INCLUDE CLASS ALL
GET http://localhost:3000/api/v1/category


### CATEGORY BY ID
GET http://localhost:3000/api/v1/category/3


### CATEGORY UPDATE
PUT http://localhost:3000/api/v1/category/2
Content-Type: application/json

{
    "categoryName":"UI/UX DESIGN UPDATE"
}

### CATEGORY BY ID
DELETE http://localhost:3000/api/v1/category/1


#### CLASS ENDPOINT GetByClassCode AND PUT ###
GET http://localhost:3000/api/v1/class?categoryId=1-3&levelName=1-4&isFree=true&search=pencarian&popular=true&latest=true
####
GET http://localhost:3000/api/v1/class/UD0

####
PUT http://localhost:3000/api/v1/class/UD0
Content-Type: application/json

{
    "className":"update",
    "description":"update",
    "price":2000,
    "levelName":"Beginner",
    "isFree":true,
    "categoryId":"1",
    "linkSosmed":"owkokw"
}

####
DELETE http://localhost:3000/api/v1/class/U0
