### Update inProgress
GET http://localhost:3000/api/v1/learning/DA0
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhhbG9AZ21haWwuY29tIiwiaWF0IjoxNzAyMzEwODIyfQ.pDNLmoXLIF1jpCiQ3JPC1PrNiN_CWhjuhQWiLoHN0KY
