### LOGIN
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
    "email":"najmulazka369@gmail.com",
    "password":"najmulazka"
}

### REGISTER
POST http://localhost:3000/api/v1/auth/register
Content-Type: application/json

{
    "namaLengkap":"imran",
    "email":"muhammadalimran22@gmail.com",
    "noTelp":"081397648082",
    "password":"imran123"
}

#### VERIVY-OTP
POST http://localhost:3000/api/v1/auth/verify-otp
Content-Type: application/json

{
    "email":"muhammadalimran22@gmail.com",
    "otp":"821187"
}

#### RESEND-OTP
POST http://localhost:3000/api/v1/auth/resend-otp
Content-Type: application/json

{
    "email":"muhammadalimran22@gmail.com"
}