### LOGIN
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
    "email":"deapark01@gmail.com",
    "password":"lili"
}

### REGISTER
POST http://localhost:3000/api/v1/auth/register
Content-Type: application/json

{
    "fullName":"Dea Lili",
    "email":"deapark01@gmail.com",
    "noTelp":"085326678543",
    "password":"lili"
}

### change-password
POST http://localhost:3000/api/v1/auth/change-password
Content-Type: application/json

{
    "email":"muhammadalimran22@gmail.com",
    "currentPassword":"",
    "new_password":"",
    "new_password_confirm":""
}

#### VERIVY-OTP
POST http://localhost:3000/api/v1/auth/verify-otp
Content-Type: application/json

{
    "email":"deapark01@gmail.com",
    "activationCode":"741486"
}

####
GET http://localhost:3000/api/v1/auth/resend-otp?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im11aGFtbWFkYWxpbXJhbjIyQGdtYWlsLmNvbSIsImlhdCI6MTcwMDkwNzMwMX0.UIWbCdaX9wjr4BoeEPPF8480boZl2vaI8HDzJ2kg80g

#### RESEND-OTP
POST http://localhost:3000/api/v1/auth/resend-otp?token=
Content-Type: application/json

{
    "email":"muhammadalimran22@gmail.com"
}

#### FORRGOT-PASSWORD
POST http://localhost:3000/api/v1/auth/forrgot-password
Content-Type: application/json

{
    "email":"najmulazka369@gmail.com"
}

#### RESEND OTP PASSWORD
GET http://localhost:3000/api/v1/auth/resend-otp-password?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5ham11bGF6a2EzNjlAZ21haWwuY29tIiwiaWF0IjoxNzAxMDg1NTYzfQ.4HdBeds0y4qClAHOiqS2B8cNLb_L2B51SCj8Ac5EmS8

#### VERIFY OTP PASSWORD
POST http://localhost:3000/api/v1/auth/verify-otp-password?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5ham11bGF6a2EzNjlAZ21haWwuY29tIiwiaWF0IjoxNzAxMDg1NTYzfQ.4HdBeds0y4qClAHOiqS2B8cNLb_L2B51SCj8Ac5EmS8
Content-Type: application/json

{
    "otp":"617158"
}

#### GET ALL CLASS
GET http://localhost:3000/api/v1/class