name: Deploy to Railway DEV Environment

on:
  push:
    branches:
      - 'develop'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install NodeJS 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install Packages
        run: npm install

      - name: Install Railway CLI
        run: npm i -g @railway/cli

      - name: Run Migration
        run: railway run --service ${{secrets.RAILWAY_SERVICE_ID}} npx prisma migrate deploy
        env:
          RAILWAY_TOKEN: ${{secrets.RAILWAY_DEV_TOKEN}}

      - name: Deploy to Railway(dev)
        run: railway up --service ${{secrets.RAILWAY_SERVICE_ID}}
        env:
          RAILWAY_TOKEN: ${{secrets.RAILWAY_DEV_TOKEN}}
